openapi: 3.0.3
info:
  title: Lethean VPN client OpenAPI
  description: |-
    This is Lethean VPN API definition
  license:
      name: GPLv3
  version: "1.0"

paths:
  /api/vdp:
    get:
      summary: Get VDP
      description: Get VPN Description Protocol containing all known Spaces and Gateways
      operationId: getVdp
      parameters:
        - in: query
          name: checkOnly
          schema:
            type: boolean
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vdp'
        '401':
          description: Access token is missing or invalid
        '402':
          description: Access token is missing or invalid
        '403':
          description: Access token is missing or invalid
        '500':
          description: server error
    post:
      summary: Post new VDP to client
      description: Post new VDP to client
      operationId: pushVdp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vdp'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vdp'
        '401':
          description: Access token is missing or invalid
        '402':
          description: Access token is missing or invalid
        '403':
          description: Access token is missing or invalid
        '443':
          description: Error in VDP
        '500':
          description: Server error

  /api/connect/{sessionid}:
    get:
      summary: Connect existing prepaid session
      description: Connect existing prepaid session
      operationId: Connect
      parameters:
        - in: path
          name: sessionid
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Connected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connection'
        '400':
          description: Bad request
        '401':
          description: Access token is missing or invalid
        '402':
          description: Awaiting payment
        '403':
          description: Access token is missing or invalid
        '404':
          description: Session not found
        '405':
          description: Session expired
        '460':
          description: Unknown/bad space
        '461':
          description: Unknown/bad gate
        '462':
          description: Cannot use this space/gate combination
        '500':
          description: Server error

  /api/disconnect/{connectionid}:
    get:
      parameters:
        - in: path
          name: connectionid
          schema:
            type: string
          required: true
      summary: Disconnect connection
      description: Disconnect connection
      operationId: Disconnect
      responses:
        '200':
          description: Disconnected
        '401':
          description: Access token is missing or invalid
        '403':
          description: Access token is missing or invalid
        '404':
          description: Bad connection ID
        '500':
          description: Server error

  /api/connections:
    get:
      summary: Get Active connections
      description: Get active connections
      operationId: getConnections
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connections'
        '401':
          description: Access token is missing or invalid
        '403':
          description: Access token is missing or invalid
        '500':
          description: Server error

  /api/session:
    post:
      summary: Prepare session to connect to Space using Gate
      description: Prepare session to connect to Space using Gate
      operationId: Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionRequest'
      responses:
        '200':
          description: Connected
        '400':
          description: Bad request
        '401':
          description: Access token is missing or invalid
        '402':
          description: Waiting for payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '403':
          description: Access token is missing or invalid
        '460':
          description: Unknown/bad space
        '461':
          description: Unknown/bad gate
        '462':
          description: Cannot use this space/gate combination
        '500':
          description: Server error
    get:
      summary: Get session info
      description: Get session info
      operationId: getSession
      parameters:
        - in: query
          name: sessionid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '401':
          description: Access token is missing or invalid
        '402':
          description: Waiting for payment
        '403':
          description: Access token is missing or invalid
        '404':
          description: Session not found
        '500':
          description: Server error

  /api/sessions:
    get:
      summary: Get client sessions
      description: Get sessions. This means all prepaid sessions, some of them can be connected, some disconnected
      operationId: getSessions
      parameters:
        - in: query
          name: active
          schema:
            type: boolean
            default: False
        - in: query
          name: notpaid
          schema:
            type: boolean
            default: False
        - in: query
          name: expired
          schema:
            type: boolean
            default: False
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sessions'
        '401':
          description: Access token is missing or invalid
        '403':
          description: Access token is missing or invalid
        '500':
          description: Server error

  /api/pay/session/{sessionid}:
    get:
      summary: Pay for session
      description: Pay for session - send payment from local wallet to provider
      operationId: paySession
      parameters:
        - in: path
          name: sessionid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '201':
          description: Already paid
        '401':
          description: Access token is missing or invalid
        '402':
          description: Awaiting payment
        '403':
          description: Access token is missing or invalid
        '404':
          description: Session not found
        '500':
          description: Server error

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:

# Openapi providers definition
###################################

    Provider:
      type: object
      additionalProperties: false
      properties:
        filetype:
          type: string
          enum:
            - LetheanProvider
        version:
          type: string
          enum:
            - "1.0"
        providerid:
          type: string
        name:
          type: string
        description:
          type: string
        ca:
          type: array
          items:
            type: string
        manager-url:
          type: string
        spaces:
          type: array
          items:
            type: string
        wallet:
          type: string
      required:
        - filetype
        - version
        - providerid
        - name
        - manager-url
        - spaces
        - ca

    Providers:
      type: array
      items:
        $ref: '#/components/schemas/Provider'
# Gate openapi specifications
###################################

    Gate:
      type: object
      additionalProperties: false
      properties:
        filetype:
          type: string
          enum:
            - LetheanGateway
        version:
          type: string
          enum:
            - "1.0"
        providerid:
          type: string
        gateid:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: object
          additionalProperties: false
          properties:
            per-day:
              type: number
        internal:
          type: boolean
          default: false
        type:
          type: string
          enum:
            - wg
            - http-proxy
            - socks-proxy
            - daemon-rpc-proxy
            - daemon-p2p-proxy
            - wg-tcp
            - ssh
            - tls-ssh
        wg:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tcp_port:
              type: integer
            public_key:
              type: string
        http-proxy:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tls:
              type: boolean
        socks-proxy:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tls:
              type: boolean
        daemon-p2p-proxy:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tls:
              type: boolean
            coin:
              type: string
              default: lethean
              enum:
                - lethean
                - monero
        daemon-rpc-proxy:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tls:
              type: boolean
            coin:
              type: string
              default: lethean
              enum:
                - lethean
                - monero
        ssh:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            username:
              type: string
            tls:
              type: boolean
          required:
            - host
            - port
            - username
        spaces:
          type: array
          items:
            type: string
        gates:
          type: array
          items:
            type: string
        replaces:
          type: string
        gate-types:
          type: array
          items:
            type: string
            enum:
              - wg
              - http-proxy
              - socks-proxy
              - daemon-rpc
              - daemon-p2p
              - wg-tcp
              - ssh
              - ssh-tls
      required:
        - gateid
        - name
        - providerid
        - version
        - filetype
        - type
        - spaces

    Gates:
      type: array
      items:
        $ref: '#/components/schemas/Gate'
# Openapi space definition
###################################

    Space:
      type: object
      additionalProperties: false
      properties:
        filetype:
          type: string
          enum:
            - LetheanSpace
        version:
          type: string
          enum:
            - "1.0"
        providerid:
          type: string
        spaceid:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: object
          additionalProperties: false
          properties:
            per-day:
              type: number
        ips:
          type: array
          items:
            type: string
        dns_servers:
          type: array
          items:
            type: string
      required:
        - spaceid
        - providerid
        - filetype
        - version
# Session definition
###################################

    Session:
      type: object
      additionalProperties: false
      properties:
        spaceid:
          type: string
        gateid:
          type: string
        created:
          type: integer
        username:
          type: string
        password:
          type: string
        bearer:
          type: string
        wallet:
          type: string
        price:
          type: number
        days:
          type: integer
        paid:
          type: boolean
        parent:
          type: string
        payments:
          type: array
          items:
            $ref: '#/components/schemas/Payment'
        paymentid:
          type: string
        activated:
          type: integer
        payment_sent:
          type: string
        wg:
          $ref: '#/components/schemas/WgSessionData'
        proxy:
          $ref: '#/components/schemas/ProxySessionData'
        ssh:
          $ref: '#/components/schemas/SSHSessionData'
        sessionid:
          type: string
        expires:
          type: integer
      required:
        - created
        - sessionid
        - paymentid
        - wallet
        - price
        - days
        - expires

    Sessions:
      type: array
      items:
        $ref: '#/components/schemas/Session'

    Payment:
      type: object
      additionalProperties: false
      properties:
        height:
          type: number
        txid:
          type: string
        amount:
          type: number

    SessionRequest:
      type: object
      additionalProperties: false
      properties:
        spaceid:
          type: string
        gateid:
          type: string
        days:
          type: integer
        like_sessionid:
          type: string
      required:
        - spaceid
        - gateid
        - days

    WgSessionData:
      type: object
      additionalProperties: false
      properties:
        ip:
          type: string
        network_bits:
          type: integer
        gw:
          type: string
        dns:
          type: string

    ProxySessionData:
      type: object
      additionalProperties: false
      properties:
        key:
          type: string
        crt:
          type: string
      required:
        - key
        - crt

    SSHSessionData:
      type: object
      additionalProperties: false
      properties:
        key:
          type: string
        crt:
          type: string
        port:
          type: number
      required:
        - key
        - crt

# Openapi VDP definition
###################################

    Vdp:
      type: object
      additionalProperties: false
      properties:
        filetype:
          type: string
          enum:
            - VPNDescriptionProtocol
        version:
          type: string
          enum:
            - "1.0"
        spaces:
          type: array
          items:
            $ref: '#/components/schemas/Space'
        gates:
          type: array
          items:
            $ref: '#/components/schemas/Gate'
        providers:
          type: array
          items:
            $ref: '#/components/schemas/Provider'
      required:
        - filetype
        - version
# Session definition
###################################

    Connection:
      type: object
      additionalProperties: false
      properties:
        connectionid:
          type: string
        sessionid:
          type: string
        parent:
          type: string
        children:
          type: array
          items:
            type: string
        port:
          type: number
        data:
          type: object
      required:
        - connectionid
        - sessionid

    Connections:
      type: array
      items:
        $ref: '#/components/schemas/Connection'
